# Generated by zen0x — do not edit by hand
[Settings]
gtk-theme-name={{ meta.gtk_theme }}
gtk-icon-theme-name={{ meta.icon_theme }}
gtk-application-prefer-dark-theme={{ derived.prefer_dark }}
gtk-cursor-theme-name=Sunset-cursors
gtk-cursor-theme-size=24
