#!/bin/bash

# zen0x:summary=Launch a TUI command in the default terminal with Zen0x styling
# zen0x:args=<command> [args...]

APP_ID="org.zen0x.$(basename "$1")"
exec setsid uwsm-app -- footclient --app-id="$APP_ID" -e "$@"
